title: Armin Maddah
description: Data Analyst / Research Specialist
author:
  name: Armin Maddah 
  nickname: madi
  twitter: armin_neuro
hostname:  # used to determine if google analytics should be triggered
url:  # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Armin Maddah
  links:
    - https://twitter.com/armin_neuro
    - https://https://github.com/armin-neuro
    - https://www.linkedin.com/in/armin-maddah/
    - https://www.last.fm/user/blue3in


twitter:
  username: armin_neuro

# main page content

links:
  - name: github
    url: https://github.com/armin-neuro
    class: fab fa-github
  - name: twitter
    url: https://twitter.com/armin_neuro
    class: fab fa-twitter
  - name: linkedin
    url: https://www.linkedin.com/in/armin-maddah/
    class: fab fa-linkedin-in
  - name: last.fm
    url: https://www.last.fm/user/blue3in
    class: fab fa-lastfm

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
